const Url = require('../models/Url');

// Create short URL
exports.createShortUrl = async (req, res) => {
  try {
    console.log('Request body:', req.body);
    const { longUrl } = req.body;

    if (!longUrl) {
      return res.status(400).json({ message: 'Long URL is required' });
    }

    // Check if URL already exists
    let url = await Url.findOne({ longUrl });
    if (url) {
      return res.json(url);
    }

    // Create new URL
    url = new Url({
      longUrl,
    });

    // shortCode is auto-generated by schema, set shortUrl before saving
    url.shortUrl = `http://localhost:5000/api/urls/${url.shortCode}`;
    
    await url.save();
    
    res.status(201).json(url);
  } catch (error) {
    console.error('Error creating short URL:', error);
    res.status(500).json({ message: error.message });
  }
};

// Get all URLs
exports.getAllUrls = async (req, res) => {
  try {
    const urls = await Url.find().sort({ createdAt: -1 });
    res.json(urls);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Redirect to long URL
exports.redirectToLongUrl = async (req, res) => {
  try {
    const { shortCode } = req.params;
    const url = await Url.findOne({ shortCode });

    if (!url) {
      return res.status(404).json({ message: 'Short URL not found' });
    }

    // Increment clicks
    url.clicks += 1;
    await url.save();

    res.redirect(url.longUrl);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Delete URL
exports.deleteUrl = async (req, res) => {
  try {
    const { id } = req.params;
    const url = await Url.findByIdAndDelete(id);

    if (!url) {
      return res.status(404).json({ message: 'URL not found' });
    }

    res.json({ message: 'URL deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
